#ifndef CODES_H
#define CODES_H

#define SUCCESS 0
#define FAILURE 1
#define JUDGE_ERROR 2



#define LOGIN_ATTEMPT 0
#define SIGNUP_ATTEMPT 1
#define LOGOUT_ATTEMPT 2
#define ADD_PROBLEM 3
#define UPDATE_PROBLEM 4
#define GET_PROBLEM 5
#define DELETE_PROBLEM 6
#define VIEW_ALL_PROBLEMS 7
#define VIEW_A_PROBLEM 8
#define SUBMIT_SOLUTION 9
#define DUEL_USER 10
#define WITHDRAW_CHALLENGE 11
#define VIEW_DUEL_PROBLEM_STATEMENT 12
#define SUBMIT_DUEL_SOLUTION 13
#define FORFEIT_DUEL 14
#define DUEL_ACCEPTED 15
#define VIEW_FULL_LEADERBOARD 16
#define VIEW_SPECIFIC_ELO 17

#define GO_TO_LOGIN_MENU 1000
#define GO_TO_MODIFY_PROBLEMS_MENU 1001
#define GO_TO_ADMIN_MENU 1002
#define GO_TO_USER_MENU 1003
#define GO_TO_DUEL_WAITING_MENU 1004
#define GO_TO_DUEL_MENU 1005

#define EASY_PROBLEM 0
#define MEDIUM_PROBLEM 1
#define HARD_PROBLEM 2

#define REGULAR_USER 0
#define ADMIN_USER 1
#define PROBLEM_SETTER_USER 2

#define LOGIN_MENU 0
#define ADMIN_MENU 1
#define USER_MENU 2
#define MODIFY_PROBLEMS_MENU 3
#define DUEL_MENU 4

#define PROBLEM_VISIBLE 1
#define PROBLEM_HIDDEN 0

#define MATCH_FOUND 101
#define ADDED_TO_CHALLENGE_QUEUE 102

#endif